### PR TITLE
Add Support for SourceLocation and ScriptSourceLocation Using Same URI

### LINKED ISSUE #384: Find-module/find-script does not find any modules/scripts hosted on a private nuget feed.
I have an environment where we have a [self-hosted nuget server instance](https://github.com/NuGet/NuGet.Server) that has been set up to have [multiple nuget feeds](https://docs.microsoft.com/en-us/nuget/hosting-packages/nuget-server).  One of these nuget feeds is going to be used to host powershell modules and scripts.  I have installed the latest packagemanagement and powershellget powershell modules, and registered the nuget feed in question with register-psrepository.  I then attempted to publish a test module to this newly registered nuget feed.  The command did not return an error, so, in an attempt to verify that the module was pushed, I ran a "find-module" command to return a modules hosted on the registered repository.  However, find-module did not return any hosted modules.  After some testing, I found that the powershell module had actually been published to the nuget feed, as I could save and install the module from the repository and the module was listed in the nuget server's package directory.  Therefore, I can only conclude that find-module does not work when querying a repository hosted on a self-hosted nuget server.  [Here](https://showmore.com/u/34pn9ub) is a video displaying the issue.

**UPDATE:**  The same behavior is occurring with scripts as well.

Steps to reproduce
------------------
For a nuget feed setup as indicated above and register one of the nuget feeds:
```powershell
Register-PSRepository -Name Test2 -SourceLocation "http://localhost:8180/nugetfeed" -PublishLocation "http://localhost:8180/nugetfeed" -PackageManagementProvider nuget -InstallationPolicy Trusted
Publish-Module -Path "C:\path\to\module" -NuGetApiKey "<nugetapikey>" -Repository "Test2" -Force -Confirm:$false
Find-Module -Filter * -Repository "Test2"  #This returns nothing
save-module -Name "<modulename>" -Repository "Test2" -Path C:\temp -Force -Confirm:$false  #But this will download the module successfully.
```

Expected behavior
-----------------
Find-module should return the module I just published to the private nuget feed
```none

```

Actual behavior
---------------
Find-module returns nothing.
```none

```

Environment data
----------------

```powershell
$PSVersionTable

Name                           Value                                                                                                               
----                           -----                                                                                                               
PSVersion                      5.1.14409.1018                                                                                                      
PSEdition                      Desktop                                                                                                             
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                             
BuildVersion                   10.0.14409.1018                                                                                                     
CLRVersion                     4.0.30319.42000                                                                                                     
WSManStackVersion              3.0                                                                                                                 
PSRemotingProtocolVersion      2.3                                                                                                                 
SerializationVersion           1.1.0.1          

```

```powershell
> Get-Module -ListAvailable PowerShellGet,PackageManagement


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                                                         
---------- -------    ----                                ----------------                                                                         
Script     1.2.4      PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}                   
Binary     1.0.0.1    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}                   
Script     2.0.3      PowerShellGet                       {Find-Command, Find-DSCResource, Find-Module, Find-RoleCapability...}                    
Script     1.5.0.0    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}                             
Script     1.0.0.1    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}    

```

```powershell
> Get-PackageProvider -ListAvailable

Name                     Version          DynamicOptions                                                                                           
----                     -------          --------------                                                                                           
Chocolatey               2.8.5.130        SkipDependencies, ContinueOnFailure, ExcludeVersion, ForceX86, PackageSaveMode, FilterOnTag, Contains,...
msi                      3.0.0.0          AdditionalArguments                                                                                      
msu                      3.0.0.0                                                                                                                   
nuget                    2.8.5.208                                                                                                                 
NuGet                    3.0.0.1          Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag, Contains, AllowPrereleaseV...
PowerShellGet            2.0.3.0          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, InstallUpdate, NoPathUpdate,...
PowerShellGet            1.5.0.0                                                                                                                   
PowerShellGet            1.0.0.1                                                                                                                   
Programs                 3.0.0.0          IncludeWindowsInstaller, IncludeSystemComponent                                                          


```

### PR DESCRIPTION
**Pull request by ThomasNieto**
This PR closes #384 and #76.

### CODE REVIEW

**Comment by alerickson** [comment]
@tnieto88 thanks for the PR!  Could you add a test for both of those fixes?  Though I'm more concerned with testing for #384.

**Comment by ThomasNieto** [comment]
@alerickson I'll get some tests added.

**Comment by ThomasNieto** [comment]
@alerickson Tests have been added.

**Comment by alerickson** [comment]
Thank you @tnieto88!

**Pull request merged**
