### PR TITLE
Update LICENSE so that it's recognized as MIT

### PR DESCRIPTION
**Pull request by xtqqczze**
* Update LICENSE so that Github recognizes it as MIT.
* Remove the term All Rights Reserved as Microsoft no longer recommend it.

See also: https://github.com/PowerShell/PowerShell/pull/12729

### CODE REVIEW

**Comment by Tyler887** [comment]
@lzybkr This PR was made 2 years ago and there was no activity on it, so we should close it and open an issue to raise this problem more easily.

**Comment by lzybkr** [comment]
@SteveL-MSFT can do that.

**Comment by xtqqczze** [comment]
Issue opened: #680.

**Comment by xtqqczze** [comment]
Superseded by #682.

**Pull request closed without merging**
