### PR TITLE
Updated CI pipeline for testing PSModule DSC resources

### PR DESCRIPTION
**Pull request by johlju**
I opened the issue https://github.com/PowerShell/ComputerManagementDsc/issues/205 to add a resource to the DSC resource module, where @PlagueHO mentioned that there was a new resource here. Instead of re-invent the wheel I figure I help out making this resource better instead. 🙂 

I'm interested if there need to be made more changes to the build pipeline (more than I have done already) for this resource to be released.
If it is not gonna be release together with the PowerShellGet module then I'm interested in how it is gonna be released.

**Changes:**

* Update the AppVeyor CI test pipeline with a new job to run tests for
  the DSC resources, primarily for the resource `PSModule`.
  The new job uses the test framework used for the DSC Resource Kit,
  the [DscResource.Tests](https://github.com/PowerShell/DscResource.Tests) repository.
* Update .gitignore to ignore the [DscResource.Tests](https://github.com/PowerShell/DscResource.Tests)
  test framework. When running unit test locally it is cloned into the
  local repository folder.
* Added module PowerShellGet.LocalizationHelper containing localization
  helper functions for DSC resources, and unit tests for the helper
  functions.
* Moved helper functions for the DSC resource `PSModule` to the module
  PowerShellGet.ResourceHelper. Added improved localization support, and
  code formatting against workspace VS Code settings.
* Changes to PSModule.
  * Added improved localization support.
  * Changed type on the parameters that had `[Switch]` to correctly use
    `Systen.Boolean` to match the schema.mof.
  * Code formatting against workspace VS Code settings.
  * Added unit tests.
  * Added integration tests
  * It is now possible to install a module and passing in `AllowClobber`
    when the modules package source is trusted (it already worked in
    other scenarios).
* Changed the AppVeyor CI build pipeline so it added the DSC resource
  `PSModule` and dependent helper modules (the `Modules` folder) to the
  AppVeyor artifact.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/powershellget/413)

### CODE REVIEW

**Comment by johlju** [comment]
This PR is ready for review now!

**Comment by alerickson** [comment]
Hi Johan,
Thanks for your contribution!  In general this PR looks good.  I see that you created a new dir, PowerShellGet, in the root.  Could you change the name just so it's a clearer distinction from the PowerShellGet module itself, or just remove the directory to have DSCResources in the root?

**Comment by johlju** [comment]
The folder was there to begin with, but I agree and also felt, it should be renamed to something else. 
I will look into the possibility to remove the folder entirely, if that doesn’t work I will rename it to something better.

**Comment by johlju** [comment]
@alerickson I had to rename the folder, the other options would have been too much (unnecessary) work. 

I tested moving the folder both to the root of the repository, and to the `/src/PowerShellGet` folder, but both turned out having different kind of problems. The DscResource.Tests has a lot of logic in it for testing resources, but it also have a lot of style checks that is not compliant with this entire module, it resulted in a lot of failing tests. And removing the DscResource.Tests I would have to invent the wheel again making sure the integration tests was working correctly (with certificate testing, and downloading of dependent modules, etc.). It was just easier to rename the folder, and keep a separate build worker running DSC tests.

**Comment by johlju** [comment]
@alerickson This one is ready for review again.

**Comment by alerickson** [comment]
Thanks for those changes!

**Comment by johlju** [comment]
Thank you! Hoping that resource will be released soon so we can start using it. :smile:

**Pull request merged**
